name: app
description: A new Flutter project.
publish_to: 'none'
version: 1.1.5+4

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  flutter_native_timezone: ^2.0.0
  timezone: ^0.9.0
  sqflite: ^2.1.0+1
  flutter_local_notifications: ^12.0.3+1
  audioplayers: ^1.1.1
  fl_chart: ^0.55.2
  flutter_time_picker_spinner: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.2.11

flutter_native_splash:
  color: "#ffffff"
  image: assets/splash.png

flutter:
  uses-material-design: true

  assets:
    - assets/click.wav
    - assets/hero.png